server:
  port: 5000

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER_SERVICE
            uri:
              lb://USER_SERVICE
            predicates:
              - Path=/auth/**, /users/**, /api/users/**, /

          - id: PROJECT_SERVICE
            uri:
              lb://PROJECT_SERVICE
            predicates:
              - Path=/api/project/**, /project/**

          - id: SUBMISSION_SERVICE
            uri:
              lb://SUBMISSION_SERVICE
            predicates:
              - Path=/api/submissions/**, /submissions/**

          - id: REPORT_SERVICE
            uri:
              lb://REPORT_SERVICE
            predicates:
              - Path=/api/reports/**, /reports/**

          - id: EMAIL_SERVICE
            uri:
              lb://EMAIL_SERVICE
            predicates:
              - Path=/email/**, /email/**

          - id: NOTIFICATION_SERVICE
            uri:
              lb://NOTIFICATION_SERVICE
            predicates:
              - Path=/api/notifications/**, /notifications/**

        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          cors-configuration:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
