server:
 port: 5001

spring:
 application:
  name: USER-SERVICE

  spring:
   jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
   datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver


