spring:
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/pms_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: TODO
    password: TODO
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
